language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
    matrix:
        - COMPOSER_FLAGS=""
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - COMPOSER_FLAGS="--prefer-stable"

before_script:
    - composer clearcache
    - composer update $COMPOSER_FLAGS
    - bin/install-moco.sh

script:
    - vendor/bin/atoum
    - vendor/bin/behat -f progress
